### ISSUE TITLE
Feature: add API method: updateFeature(<crossfilter>, <options>)

### ISSUE THREAD

**Issue by hergert** [yagoferrer/gmplus#102]
First parameter contains either: crossfilter, uid or an instance of the feature.

**Comment by yagoferrer** [comment]
GMP.maps.myMap.json.all -> all shapes
GMP.maps.myMap.json.groups -> by Group
GMP.maps.myMap.json.groups[idPropertyName]

**Comment by yagoferrer** [comment]
I think is better if we just allow crossfilter dimensions for any of the properties.

**Comment by yagoferrer** [comment]
This is important to get done for 0.4.0
